version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'RMS'
      MYSQL_USER: 'rms'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10

#  app:
#    container_name: spring-boot-app
#    image: nasanbuyan/team7-rms-app:latest
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/RMS?useSSL=false&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: rms
#      SPRING_DATASOURCE_PASSWORD: password
#    ports:
#      - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy

volumes:
  mysql-data:
